swagger: '2.0'
info:
  title: Bank Argent API - Accounts & Transactions
  description: API endpoints for managing user bank accounts and their transactions
  version: '1.0.1'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
tags:
  - name: Bank Account Module
    description: Endpoints for managing bank accounts
  - name: Transaction Module
    description: Endpoints for managing transactions linked to accounts
paths:
  /bank-accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Bank Account Module
      summary: Get user bank accounts
      description: Returns the list of bank accounts belonging to the authenticated user
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Bearer token
      produces:
        - application/json
      responses:
        200:
          description: List of user's bank accounts
          schema:
            type: array
            items:
              $ref: '#/definitions/BankAccount'
        401:
          description: Unauthorized

  /bank-accounts/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Bank Account Module
      summary: Get bank account detail
      description: Returns detailed information about a specific bank account
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Bank account details
          schema:
            $ref: '#/definitions/BankAccount'
        404:
          description: Account not found

  /bank-accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transactions for a specific account
      description: Returns all transactions for a specific account and month
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
        - name: month
          in: query
          required: false
          type: string
          description: Month in format YYYY-MM
        - name: Authorization
          in: header
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Transactions for the account
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        404:
          description: Account not found

  /bank-accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transaction detail
      description: Returns detail of a single transaction from a specific account
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Transaction detail
          schema:
            $ref: '#/definitions/Transaction'
        404:
          description: Transaction or account not found

    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction (category or notes)
      description: Update note or category for a transaction under a specific account
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        200:
          description: Transaction updated
          schema:
            $ref: '#/definitions/Transaction'
        400:
          description: Invalid input
        404:
          description: Transaction or account not found

definitions:
  BankAccount:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
        example: "Argent Bank Checking"
      type:
        type: string
        example: "checking"
      number:
        type: string
        example: "x8349"
      balance:
        type: number
        format: float
      currency:
        type: string
        example: "USD"

  Transaction:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: string
      date:
        type: string
      description:
        type: string
      amount:
        type: number
        format: float
      balance:
        type: number
        format: float
      type:
        type: string
      category:
        type: string
      notes:
        type: string

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header